/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated/contratos/index'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated/contratos/$id'
import { Route as AuthenticatedContratosNovoRouteImport } from './routes/_authenticated/contratos/novo'
import { Route as AuthenticatedDemandasIndexRouteImport } from './routes/_authenticated/demandas/index'
import { Route as AuthenticatedDemandasIdRouteImport } from './routes/_authenticated/demandas/$id'
import { Route as AuthenticatedDemandasDeEmailRouteImport } from './routes/_authenticated/demandas/de-email'
import { Route as AuthenticatedDemandasNovaRouteImport } from './routes/_authenticated/demandas/nova'
import { Route as AuthenticatedEscritoriosIndexRouteImport } from './routes/_authenticated/escritorios/index'
import { Route as AuthenticatedEscritoriosIdRouteImport } from './routes/_authenticated/escritorios/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/contratos/$id',
    path: '/contratos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosNovoRoute =
  AuthenticatedContratosNovoRouteImport.update({
    id: '/contratos/novo',
    path: '/contratos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandasIndexRoute =
  AuthenticatedDemandasIndexRouteImport.update({
    id: '/demandas/',
    path: '/demandas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandasIdRoute = AuthenticatedDemandasIdRouteImport.update({
  id: '/demandas/$id',
  path: '/demandas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandasDeEmailRoute =
  AuthenticatedDemandasDeEmailRouteImport.update({
    id: '/demandas/de-email',
    path: '/demandas/de-email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandasNovaRoute =
  AuthenticatedDemandasNovaRouteImport.update({
    id: '/demandas/nova',
    path: '/demandas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscritoriosIndexRoute =
  AuthenticatedEscritoriosIndexRouteImport.update({
    id: '/escritorios/',
    path: '/escritorios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscritoriosIdRoute =
  AuthenticatedEscritoriosIdRouteImport.update({
    id: '/escritorios/$id',
    path: '/escritorios/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mfa': typeof MfaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/api/chat': typeof ApiChatRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/demandas/de-email': typeof AuthenticatedDemandasDeEmailRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/escritorios/$id': typeof AuthenticatedEscritoriosIdRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/demandas/': typeof AuthenticatedDemandasIndexRoute
  '/escritorios/': typeof AuthenticatedEscritoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mfa': typeof MfaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/api/chat': typeof ApiChatRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/demandas/de-email': typeof AuthenticatedDemandasDeEmailRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/escritorios/$id': typeof AuthenticatedEscritoriosIdRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/demandas': typeof AuthenticatedDemandasIndexRoute
  '/escritorios': typeof AuthenticatedEscritoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mfa': typeof MfaRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/_authenticated/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/_authenticated/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/_authenticated/demandas/de-email': typeof AuthenticatedDemandasDeEmailRoute
  '/_authenticated/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/_authenticated/escritorios/$id': typeof AuthenticatedEscritoriosIdRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/_authenticated/demandas/': typeof AuthenticatedDemandasIndexRoute
  '/_authenticated/escritorios/': typeof AuthenticatedEscritoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mfa'
    | '/assistente'
    | '/configuracoes'
    | '/painel'
    | '/seguranca'
    | '/api/chat'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/demandas/$id'
    | '/demandas/de-email'
    | '/demandas/nova'
    | '/escritorios/$id'
    | '/contratos/'
    | '/demandas/'
    | '/escritorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mfa'
    | '/assistente'
    | '/configuracoes'
    | '/painel'
    | '/seguranca'
    | '/api/chat'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/demandas/$id'
    | '/demandas/de-email'
    | '/demandas/nova'
    | '/escritorios/$id'
    | '/contratos'
    | '/demandas'
    | '/escritorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mfa'
    | '/_authenticated/assistente'
    | '/_authenticated/configuracoes'
    | '/_authenticated/painel'
    | '/_authenticated/seguranca'
    | '/api/chat'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/contratos/novo'
    | '/_authenticated/demandas/$id'
    | '/_authenticated/demandas/de-email'
    | '/_authenticated/demandas/nova'
    | '/_authenticated/escritorios/$id'
    | '/_authenticated/contratos/'
    | '/_authenticated/demandas/'
    | '/_authenticated/escritorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MfaRoute: typeof MfaRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/novo': {
      id: '/_authenticated/contratos/novo'
      path: '/contratos/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof AuthenticatedContratosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/': {
      id: '/_authenticated/demandas/'
      path: '/demandas'
      fullPath: '/demandas/'
      preLoaderRoute: typeof AuthenticatedDemandasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/$id': {
      id: '/_authenticated/demandas/$id'
      path: '/demandas/$id'
      fullPath: '/demandas/$id'
      preLoaderRoute: typeof AuthenticatedDemandasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/de-email': {
      id: '/_authenticated/demandas/de-email'
      path: '/demandas/de-email'
      fullPath: '/demandas/de-email'
      preLoaderRoute: typeof AuthenticatedDemandasDeEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/nova': {
      id: '/_authenticated/demandas/nova'
      path: '/demandas/nova'
      fullPath: '/demandas/nova'
      preLoaderRoute: typeof AuthenticatedDemandasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escritorios/': {
      id: '/_authenticated/escritorios/'
      path: '/escritorios'
      fullPath: '/escritorios/'
      preLoaderRoute: typeof AuthenticatedEscritoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escritorios/$id': {
      id: '/_authenticated/escritorios/$id'
      path: '/escritorios/$id'
      fullPath: '/escritorios/$id'
      preLoaderRoute: typeof AuthenticatedEscritoriosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRoute
  AuthenticatedContratosNovoRoute: typeof AuthenticatedContratosNovoRoute
  AuthenticatedDemandasIdRoute: typeof AuthenticatedDemandasIdRoute
  AuthenticatedDemandasDeEmailRoute: typeof AuthenticatedDemandasDeEmailRoute
  AuthenticatedDemandasNovaRoute: typeof AuthenticatedDemandasNovaRoute
  AuthenticatedEscritoriosIdRoute: typeof AuthenticatedEscritoriosIdRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
  AuthenticatedDemandasIndexRoute: typeof AuthenticatedDemandasIndexRoute
  AuthenticatedEscritoriosIndexRoute: typeof AuthenticatedEscritoriosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
  AuthenticatedContratosIdRoute: AuthenticatedContratosIdRoute,
  AuthenticatedContratosNovoRoute: AuthenticatedContratosNovoRoute,
  AuthenticatedDemandasIdRoute: AuthenticatedDemandasIdRoute,
  AuthenticatedDemandasDeEmailRoute: AuthenticatedDemandasDeEmailRoute,
  AuthenticatedDemandasNovaRoute: AuthenticatedDemandasNovaRoute,
  AuthenticatedEscritoriosIdRoute: AuthenticatedEscritoriosIdRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  AuthenticatedDemandasIndexRoute: AuthenticatedDemandasIndexRoute,
  AuthenticatedEscritoriosIndexRoute: AuthenticatedEscritoriosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MfaRoute: MfaRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
